# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build cbz-editor-server`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t cbz-editor`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system cbz-editor && \
          adduser --system -G cbz-editor cbz-editor

COPY backend/dist .
COPY frontend/dist ./public
RUN chown -R cbz-editor:cbz-editor .

CMD [ "node", "main.js" ]
